/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'message' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const MealPlanRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'planType' : IDL.Text,
});
export const OrderRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'deliveryNotes' : IDL.Text,
  'itemsRequested' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getAllMealPlanRequests' : IDL.Func(
      [],
      [IDL.Vec(MealPlanRequest)],
      ['query'],
    ),
  'getAllOrderRequests' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
  'getContactRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContactRequest)],
      ['query'],
    ),
  'getMealPlanRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MealPlanRequest)],
      ['query'],
    ),
  'getOrderRequest' : IDL.Func([IDL.Nat], [IDL.Opt(OrderRequest)], ['query']),
  'submitContactRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitMealPlanRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitOrderRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'message' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const MealPlanRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'planType' : IDL.Text,
  });
  const OrderRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'deliveryNotes' : IDL.Text,
    'itemsRequested' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getAllMealPlanRequests' : IDL.Func(
        [],
        [IDL.Vec(MealPlanRequest)],
        ['query'],
      ),
    'getAllOrderRequests' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
    'getContactRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContactRequest)],
        ['query'],
      ),
    'getMealPlanRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MealPlanRequest)],
        ['query'],
      ),
    'getOrderRequest' : IDL.Func([IDL.Nat], [IDL.Opt(OrderRequest)], ['query']),
    'submitContactRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitMealPlanRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitOrderRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };