/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactRequest {
  'id' : bigint,
  'customerName' : string,
  'message' : string,
  'phoneNumber' : string,
}
export interface MealPlanRequest {
  'id' : bigint,
  'customerName' : string,
  'address' : string,
  'phoneNumber' : string,
  'planType' : string,
}
export interface OrderRequest {
  'id' : bigint,
  'customerName' : string,
  'deliveryNotes' : string,
  'itemsRequested' : string,
  'address' : string,
  'phoneNumber' : string,
}
export interface _SERVICE {
  'getAllContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getAllMealPlanRequests' : ActorMethod<[], Array<MealPlanRequest>>,
  'getAllOrderRequests' : ActorMethod<[], Array<OrderRequest>>,
  'getContactRequest' : ActorMethod<[bigint], [] | [ContactRequest]>,
  'getMealPlanRequest' : ActorMethod<[bigint], [] | [MealPlanRequest]>,
  'getOrderRequest' : ActorMethod<[bigint], [] | [OrderRequest]>,
  'submitContactRequest' : ActorMethod<[string, string, string], bigint>,
  'submitMealPlanRequest' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'submitOrderRequest' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];